name: Docker Build
description: Build an OpenLane Docker Container
inputs:
  arch:
    description: "The Docker architecture/platform to build for"
    required: true
    default: "amd64"
  dockerhub_user:
    description: The input dockerhub user
    required: false
    default: ""
  dockerhub_password:
    description: The input dockerhub password
    required: false
    default: ""
  tool_repository:
    description: The Docker repository in which to store tools
    required: false
    default: "efabless/openlane-tools"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions/set_env_variables
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-substituters = https://openlane.cachix.org
          extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
    - name: Docker Build
      shell: bash
      run: |
        export BUILD_ARCH=${{ inputs.arch }}
        make -C docker
    - name: Export Docker Image
      shell: bash
      run: |
        docker save -o /tmp/image-${{ inputs.arch }}.tar efabless/openlane:current-${{ inputs.arch }}

    - name: Upload Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ inputs.arch }}
        path: /tmp/image-${{ inputs.arch }}.tar
