/* Generated by Yosys 0.9+932 (git sha1 5025aab, gcc 7.3.1 -fPIC -Os) */

`include "cells.v"

module striVe_levelshift(SDO_h, sdo_enb_h, xtal_ena_h, reg_ena_h, pll_vco_ena_h, pll_cp_ena_h, pll_bias_ena_h, pll_trim_h, pll_bypass_h, irq_h, porb_h, por_h, reset_h, trap_h, mfgr_id_h, prod_id_h, mask_rev_h, SDO, sdo_enb, xtal_ena, reg_ena, pll_vco_ena, pll_cp_ena, pll_bias_ena, pll_trim, pll_bypass, irq, porb, por, reset, trap, mfgr_id, prod_id, mask_rev);
  output SDO;
  input SDO_h;
  output irq;
  input irq_h;
  output [3:0] mask_rev;
  input [3:0] mask_rev_h;
  output [11:0] mfgr_id;
  input [11:0] mfgr_id_h;
  output pll_bias_ena;
  input pll_bias_ena_h;
  output pll_bypass;
  input pll_bypass_h;
  output pll_cp_ena;
  input pll_cp_ena_h;
  output [3:0] pll_trim;
  input [3:0] pll_trim_h;
  output pll_vco_ena;
  input pll_vco_ena_h;
  output por;
  input por_h;
  output porb;
  input porb_h;
  output [7:0] prod_id;
  input [7:0] prod_id_h;
  output reg_ena;
  input reg_ena_h;
  output reset;
  input reset_h;
  output sdo_enb;
  input sdo_enb_h;
  input trap;
  output trap_h;
  output xtal_ena;
  input xtal_ena_h;
  scs8hvl_lsbufhv2lv_1 ls_irq (
    .A(irq_h),
    .X(irq)
  );
  scs8hvl_lsbufhv2lv_1 \ls_mask_rev[0]  (
    .A(mask_rev_h[0]),
    .X(mask_rev[0])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mask_rev[1]  (
    .A(mask_rev_h[1]),
    .X(mask_rev[1])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mask_rev[2]  (
    .A(mask_rev_h[2]),
    .X(mask_rev[2])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mask_rev[3]  (
    .A(mask_rev_h[3]),
    .X(mask_rev[3])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[0]  (
    .A(mfgr_id_h[0]),
    .X(mfgr_id[0])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[10]  (
    .A(mfgr_id_h[10]),
    .X(mfgr_id[10])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[11]  (
    .A(mfgr_id_h[11]),
    .X(mfgr_id[11])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[1]  (
    .A(mfgr_id_h[1]),
    .X(mfgr_id[1])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[2]  (
    .A(mfgr_id_h[2]),
    .X(mfgr_id[2])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[3]  (
    .A(mfgr_id_h[3]),
    .X(mfgr_id[3])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[4]  (
    .A(mfgr_id_h[4]),
    .X(mfgr_id[4])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[5]  (
    .A(mfgr_id_h[5]),
    .X(mfgr_id[5])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[6]  (
    .A(mfgr_id_h[6]),
    .X(mfgr_id[6])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[7]  (
    .A(mfgr_id_h[7]),
    .X(mfgr_id[7])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[8]  (
    .A(mfgr_id_h[8]),
    .X(mfgr_id[8])
  );
  scs8hvl_lsbufhv2lv_1 \ls_mfgr_id[9]  (
    .A(mfgr_id_h[9]),
    .X(mfgr_id[9])
  );
  scs8hvl_lsbufhv2lv_1 ls_pll_bias_ena (
    .A(pll_bias_ena_h),
    .X(pll_bias_ena)
  );
  scs8hvl_lsbufhv2lv_1 ls_pll_bypass (
    .A(pll_bypass_h),
    .X(pll_bypass)
  );
  scs8hvl_lsbufhv2lv_1 ls_pll_cp_ena (
    .A(pll_cp_ena_h),
    .X(pll_cp_ena)
  );
  scs8hvl_lsbufhv2lv_1 \ls_pll_trim[0]  (
    .A(pll_trim_h[0]),
    .X(pll_trim[0])
  );
  scs8hvl_lsbufhv2lv_1 \ls_pll_trim[1]  (
    .A(pll_trim_h[1]),
    .X(pll_trim[1])
  );
  scs8hvl_lsbufhv2lv_1 \ls_pll_trim[2]  (
    .A(pll_trim_h[2]),
    .X(pll_trim[2])
  );
  scs8hvl_lsbufhv2lv_1 \ls_pll_trim[3]  (
    .A(pll_trim_h[3]),
    .X(pll_trim[3])
  );
  scs8hvl_lsbufhv2lv_1 ls_pll_vco_ena (
    .A(pll_vco_ena_h),
    .X(pll_vco_ena)
  );
  scs8hvl_lsbufhv2lv_1 ls_por (
    .A(por_h),
    .X(por)
  );
  scs8hvl_lsbufhv2lv_1 ls_porb (
    .A(porb_h),
    .X(porb)
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[0]  (
    .A(prod_id_h[0]),
    .X(prod_id[0])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[1]  (
    .A(prod_id_h[1]),
    .X(prod_id[1])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[2]  (
    .A(prod_id_h[2]),
    .X(prod_id[2])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[3]  (
    .A(prod_id_h[3]),
    .X(prod_id[3])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[4]  (
    .A(prod_id_h[4]),
    .X(prod_id[4])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[5]  (
    .A(prod_id_h[5]),
    .X(prod_id[5])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[6]  (
    .A(prod_id_h[6]),
    .X(prod_id[6])
  );
  scs8hvl_lsbufhv2lv_1 \ls_prod_id[7]  (
    .A(prod_id_h[7]),
    .X(prod_id[7])
  );
  scs8hvl_lsbufhv2lv_1 ls_reg_ena (
    .A(reg_ena_h),
    .X(reg_ena)
  );
  scs8hvl_lsbufhv2lv_1 ls_reset (
    .A(reset_h),
    .X(reset)
  );
  scs8hvl_lsbufhv2lv_1 ls_sdo_enb (
    .A(sdo_enb_h),
    .X(sdo_enb)
  );
  scs8hvl_lsbuflv2hv_1 ls_trap (
    .A(trap),
    .X(trap_h)
  );
  scs8hvl_lsbufhv2lv_1 ls_xtal_ena (
    .A(xtal_ena_h),
    .X(xtal_ena)
  );
  scs8hvl_lsbufhv2lv_1 ls_SDO (
    .A(SDO_h),
    .X(SDO)
  );
endmodule
