name: Bug Report
description: If OpenLane is not behaving as expected, please file a report here.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong? Be clear and concise.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you *want* to happen?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        This part is incredibly important:

        Please run the following shell command in the OpenLane root folder:

            python3 ./env.py issue-survey

        Then copy and paste the ENTIRE output in the text field below.

        If the command does not succeed, you are using an out-of-date version of OpenLane, and it is recommended that you update.
  - type: textarea
    id: environment-report
    attributes:
      label: Environment report
      render: shell
      description: Please paste the output from the previous command. It will be automatically formatted into code, so no need for backticks.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        You also need to upload some files so we can reproduce your issue.

        1. If you see a message like `Reproducible packaged: Please tarball and upload <PATH> if you're going to submit an issue` in your logs,  please compress and upload that folder by dragging the .tar.gz or the .zip file to the following text field.
        * The reproducible tarball is 100% required for OpenROAD bugs.
        * If the file is too large, you may split the upload over multiple .zip or .tar.gz files.

        2. If you don't...
            * Please compress and upload the design folder by dragging the .tar.gz or the .zip file to the following text field.
            * List the commands used to run the design.
        > **Warning:**
        > GitHub's maximum file upload size is 25 MB, so if your upload is larger than 25MB, please consider splitting it as follows:
        > for tar files: `split -b 24M <tar-file-name> "<file-tar-name>.part"`
        > for zip files: `zip -r -s 24M <zip-file-name> <directory-name>`
  - type: textarea
    id: reproduction-material
    attributes:
      label: Reproduction material
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
