- scl: sky130A/sky130_fd_sc_hd
  name: fastest_test_set
  designs:
    - ./designs/ci/inverter
    - ./designs/ci/wbqspiflash
    - ./designs/ci/APU
    - ./designs/ci/s44
    - ./designs/ci/zipdiv
    - ./designs/ci/xtea
    - ./designs/ci/usb
    - ./designs/ci/usb_cdc_core
    - ./designs/ci/manual_macro_placement_test
    - spm
    - ./designs/ci/gcd
    - ./designs/ci/caravel_upw
    - ./designs/ci/aes_user_project_wrapper
    - ./designs/ci/tt05_i2c_bert
- scl: sky130A/sky130_fd_sc_hd
  name: extended_test_set
  designs:
    - ./designs/ci/salsa20
    - ./designs/ci/aes_core
    - ./designs/ci/blabla
    - ./designs/ci/picorv32a
    - ./designs/ci/PPU
    - ./designs/ci/y_huff
    - ./designs/ci/aes
- scl: gf180mcuC/gf180mcu_fd_sc_mcu7t5v0
  name: fastest_test_set
  designs:
    - spm
    - ./designs/ci/APU
    - ./designs/ci/usb
    # - usb_cdc_core
    # - zipdiv
    # - wbqspiflash
- scl: gf180mcuC/gf180mcu_fd_sc_mcu7t5v0
  name: extended_test_set
  designs:
    - ./designs/ci/picorv32a
    - ./designs/ci/PPU
    - ./designs/ci/y_huff
