/* Generated by Yosys 0.34 (git sha1 4a1b5599258, gcc 8.3.1 -fPIC -Os) */

module inverter(in, out);
  input in;
  wire in;
  output out;
  wire out;
  wire tmp;
  assign tmp = out;
  sky130_fd_sc_hd__inv_2 _0_ (
    .A(in),
    .Y(out)
  );
endmodule
