# This is a basic workflow to help you get started with Actions
name: Update Latest Tag Reference

# Controls when the action will run.
on:
  # Triggers the workflow on push  only for the github-actions-conversion branches
  push:
    branches:
      - github-actions-conversion
    tags:
      - "v*"

jobs:
  createPullRequest:
    if: github.event.base_ref == 'refs/heads/github-actions-conversion' || github.ref == 'refs/heads/github-actions-conversion'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Tag in All Files
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/update_tag.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Latest Green Tag
          title: 'Update Latest Green Tag'
          branch: create-pull-request/green-tag-update
          base: github-actions-conversion
          delete-branch: true
          body: This PR is auto-generated to update the latest stable tag referenced in the documentation and the Makefile.
          labels: update green tag, automated pr
