name: Pull Request CI Check
on: [push, pull_request]

env:
  CROSS_BUILD: 1
  CACHE_ID: ${{ secrets.DOCKERHUB_USER }}

jobs:
  base-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [base, boost_base]
        arch: [amd64, arm64] #ppc64le
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: make -C docker push-${{matrix.component}}-${{matrix.arch}}

  tools-cache:
    runs-on: ubuntu-latest
    needs: base-cache
    strategy:
      matrix:
        component: [replace, opendp, route, opensta, yosys, antmicro_yosys, magic, openroad_app, padring, netgen, vlog2verilog, openphysyn, cvc, cugr, klayout, drcu]
        arch: [amd64, arm64] #ppc64le
    timeout-minutes: 600
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{matrix.component}}-${{matrix.arch}}-${{github.sha}}
        restore-keys: |
          ccache-${{matrix.component}}-${{matrix.arch}}-
    - run: make -C docker push-${{matrix.component}}-${{matrix.arch}}

  openlane:
    runs-on: ubuntu-latest
    needs: tools-cache
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: sudo rm -rf /opt
    - run: sudo apt-get clean
    - run: make -C docker tools
    - run: make -C docker openlane


