name: docker-build

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event.workflow_run.event != 'pull_request' || github.event.pull_request.head.repo.full_name == 'efabless/openlane' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get Image Name
        run: echo "IMAGE_NAME=efabless/openlane:${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Docker Build
        run: cd docker_build/ && make merge 

      - name: Docker Push
        if: ${{ github.event.workflow_run.event != 'pull_request' || github.event.pull_request.head.repo.full_name == 'efabless/openlane' }}
        run: docker push ${{ env.IMAGE_NAME }}

      - name: PDK installation
        run: cd ${GITHUB_WORKSPACE}/ && make IMAGE_NAME=${{ env.IMAGE_NAME }} pdk

      - name: SPM Test
        run: cd ${GITHUB_WORKSPACE}/ && make IMAGE_NAME=${{ env.IMAGE_NAME }} test
